# Arrays

The Python types we have seen so far are all built into Python; this means that they are automatically available when you start writing Python code. As with any modern language, however, programmers are always adding new functionality to Python and they often want to share their code with others.  The main way this is done is with packages.

A package contains extra object types, functions, and variables that are not included in base Python. Some packages are specialized to niche applications, while others are so popular that nearly every coder uses them.

One particular package, NumPy, sits as the foundation for scientific and data computing in Python. Many other data science packages are built on top of NumPy, so it is very important to understand its function.

[NumPy](http://www.numpy.org/) is the core of the [PyData](http://pydata.org/) ecosystem.

------

*From the NumPy Website*

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

------

We often use NumPy to work with data. In this notebook, we will begin introducing its functionality with a few simple examples.

To use the functionality provided by a package, we first have to import it into our program.  This is done with the `import` keyword. At the point at which we import a package, we can also rename it with the `as` keyword. Traditionally, `numpy` is renamed `np`. The reason that we do this is that there is a convention in the PyData community to import data packages with shorter names.


In [1]:
import numpy as np

In [2]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

This should look pretty familiar; the `arange` function is analogous to the `range` function we saw earlier. Instead of returning a range, however, this function returns something we call an *array*.

Arrays are similar to the sequences we saw earlier. For example, we can access items by their indices.

In [3]:
my_array = np.arange(20)
my_array[2] = 12
my_array

array([ 0,  1, 12,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Arrays also have some unique characteristics.  For one thing, all the objects contained in an array must be the same type.  This may seem like a pesky restriction, but it allows arrays to work very efficiently on large amounts of data.

In [4]:
my_array[5] = "shoe"

ValueError: invalid literal for int() with base 10: 'shoe'

The data type of an array can be accessed through the `dtype` property; this will give us information about all the objects stored in the array. That means that you cannot change the type of an array once it is created (unless you work around this).

In [5]:
my_array.dtype

dtype('int64')

In addition, once an array is created, its size is fixed. You cannot pop or append to an array because of the way that arrays allocate memory. The fixed size allows arrays to be optimized for high performance.

In [6]:
new_array = np.array([5,10,15,20])

In [7]:
new_array.append(5)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
new_array.pop()

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

You can see in the error messages that the arrays we are dealing with have type `'numpy.ndarray'`. This stands for *n*-dimensional array. We can make *n* anything that we want.

For example, we can create a two-dimensional matrix with uniformly distributed random numbers between 0 and 1.

In [9]:
np.random.rand(5,5)

array([[ 0.48895095,  0.53108007,  0.83126652,  0.05276777,  0.91766908],
       [ 0.559353  ,  0.2924421 ,  0.23723199,  0.74765613,  0.41449872],
       [ 0.82178602,  0.25544602,  0.08833865,  0.33556843,  0.81391929],
       [ 0.09075031,  0.81790454,  0.08966302,  0.30264293,  0.62078301],
       [ 0.90896921,  0.71795044,  0.905533  ,  0.77152949,  0.14777978]])

Or we can create a three-dimensional cube of numbers.

In [10]:
np.random.rand(5,5,5)

array([[[ 0.09292843,  0.84996543,  0.54278522,  0.4080527 ,  0.56182346],
        [ 0.8690863 ,  0.42678163,  0.20548377,  0.09391622,  0.06790999],
        [ 0.52307983,  0.5417984 ,  0.86732911,  0.76068987,  0.42596419],
        [ 0.69404209,  0.77561453,  0.816751  ,  0.62338596,  0.79767502],
        [ 0.74857871,  0.28675557,  0.38688043,  0.14561997,  0.28076885]],

       [[ 0.62731488,  0.49742754,  0.17906236,  0.06495931,  0.69149094],
        [ 0.99392801,  0.66404191,  0.15327014,  0.80213532,  0.90533983],
        [ 0.47418441,  0.22553504,  0.61280528,  0.04364573,  0.3267768 ],
        [ 0.86000949,  0.94552533,  0.67285429,  0.57253297,  0.44285915],
        [ 0.93269526,  0.04407929,  0.30999918,  0.73114912,  0.44195391]],

       [[ 0.74563477,  0.25934175,  0.45837259,  0.20245146,  0.55163637],
        [ 0.02841645,  0.99687909,  0.11617672,  0.64755513,  0.16502913],
        [ 0.99695806,  0.44996004,  0.07398955,  0.32187665,  0.43132456],
        [ 0.61212869,

We can keep going to higher and higher dimensional spaces, but doing so is outside the scope of this course.

The random numbers we generated above were drawn from a uniform probability distribution. This is a very simple distribution, equal to 1, between 0 and 1, and 0 everywhere else. NumPy gives us many other distributions to work with, however.

In [11]:
np.random?

We can see that there are a variety of functions at our disposal. Let's get some uniformly distributed random variables.

In [11]:
np.random.randn(20)

array([-0.40876326, -0.55517236, -1.32981788, -0.12438743, -0.6348719 ,
        0.28520215, -1.59223946,  1.44111822,  3.23274986, -1.341104  ,
       -0.99081505, -0.10248169,  0.66980884,  1.15958509, -0.27003221,
        0.05150114, -0.17999232,  0.00738674, -0.84577716,  1.38380398])

Now that we have this array of normal random variables, let's reshape it into a matrix. This is done with the reshape method.

In [12]:
ar = np.random.randn(20).reshape(5,4)

In [13]:
ar

array([[ 1.36002197, -0.34823936, -0.542834  , -0.21244252],
       [-0.00597218,  1.44837198, -0.74547986,  0.13732181],
       [ 1.22370968, -1.60648883, -0.3035393 ,  0.28673981],
       [ 0.64209514, -0.4504376 ,  0.35088428,  1.0969273 ],
       [ 0.07701238,  0.41407872, -0.46149942,  1.55340633]])

When you are working with data, you will often need to calculate some statistics from it. NumPy arrays have a lot of integrated common statistical functions.  To see an example, let's get the mean of our array.

In [14]:
ar.mean()

0.19568181570971172

The standard deviation is just as easy.

In [15]:
ar.std()

0.81286346187291725

Sometimes we will want to do these operations on each column or on each row. Doing so is still easy.

Here are the means of each column.

In [16]:
ar.mean(axis=0)

array([ 0.6593734 , -0.10854302, -0.34049366,  0.57239055])

Here are the means of each row.

In [18]:
ar.mean(axis=1)

array([ 0.49062575,  0.48989976, -0.33466518, -0.19144381,  0.36251969])

This lesson has only begun to scratch the surface of NumPy's capabilities.  The NumPy library is huge, and no one class could truly cover all of it. Additionally, NumPy has a partner library, SciPy (which stands for *scientific Python*), that builds on NumPy and adds a great deal of advanced functionality. We will return to NumPy later in this course. You will learn more about SciPy as you continue through the data science program.